### ISSUE TITLE
About BlitzIDE

### ISSUE THREAD

**Issue by MorningDemon515** [blitz-research/blitz3d_msvc2017#8]
BlitzIDE is unable to read characters with a byte count greater than 1, forcing them to display will result in garbled code. I am currently unsure which file in blitzide, which function is used to read/retrieve strings, and display strings. Could you please let me know? Thank you

**Comment by blitz-research** [comment]
Hi,

Yikes, it's been ages, but I the ;richedit' control the IDE is based on uses a streaming system to get/set text. Looking at mainframe.cpp, it looks like 'open' uses Editor::setText and 'save' uses Editor::getText, and these don't look too complicated:

https://github.com/blitz-research/blitz3d_msvc2017/blob/8ffb41bf6f64688191ad956fa9f7337ca71f06f9/blitzide/editor.cpp#L251
https://github.com/blitz-research/blitz3d_msvc2017/blob/8ffb41bf6f64688191ad956fa9f7337ca71f06f9/blitzide/editor.cpp#L289

I think if you want the IDE to properly handle UTF8, you'll have to at least:

* Change the blitzide windows build flags so it uses the 16 bit wide chars WCHAR Windows functions instead of CHAR. Hopefully this will mean the rich edit control will stream WCHAR instead CHARs - be an idea to check this first! Doing this will probably also break a few other things, but they shouldn't be ahrd to deal with.

* Convert UTF8 strings to WCHAR data inside setText() before they're streamed to the richedit control, and convert WCHAR data back to UTF8 strings after they're streamed out in getText().

This might just be enough to at least be able to type 'unicode' into the IDE and have it displayed via freetype or stb_truetype etc with your gxFont changes. This would still be pretty great!

Bye,
Mark

**Comment by MorningDemon515** [comment]
Thank you, Mark!

**Comment by blitz-research** [comment]
According to this page...

https://learn.microsoft.com/en-us/windows/win32/controls/about-rich-edit-controls

The standard Richedit control can already handle MBCS (multi byte character sets) which I had always assumed was pretty much utf8, but even if it's not, you should be able to convert utf8 to whatever format the richedit control uses which should be much easier than dealing with the WCHAR windows APIs.

Even better, according to this, it appears MBCS is now officially the same as utf8 and not just a subset!

https://stackoverflow.com/questions/3298569/difference-between-mbcs-and-utf-8-on-windows/3299860#3299860  

So in theory, utf8 should now/maybe 'just work' and you shouldn't need to mess around with WCHAR versions of anything, though I doubt it'll be quite that easy!

**Comment by MorningDemon515** [comment]
interesting!

**Comment by blitz-research** [comment]
I finally had a play with this today and think UTF-8 support is more or less working now!

I can paste UTF-8 text copied from my browser into the Blitz3D editor, and save and load files in UTF-8.

Plus UTF-8 string are correctly passed to the LibSGD runtime. There is one other hack I recently learned that should mean filesystem commands are UTF-8 compatible, but that's not quite in yet.

**Comment by MorningDemon515** [comment]
I have tested it and now the IDE can display UTF8 encoded text! But the debugger currently cannot support UTF8, but I resolved this issue a few days ago, so I may submit a PR
